title: TechFacile
description: Tutoriels informatiques simples et pratiques
lang: fr
url: "https://titanxxx505.github.io"
baseurl: "/techfacile"
markdown: kramdown
collections:
  tutorials:
    output: true
    permalink: /tutoriels/:name/
defaults:
  - scope:
      path: ""
      type: tutorials
    values:
      layout: tutorial
exclude:
  - README.md
